### ISSUE TITLE
Avatar image not populating from Gravatar

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-theme-lingonberry#1]
My Gravitar image is not populating. It works in the admin area but not on the website.

**Comment by flaviocopes** [comment]
I see here https://github.com/getgrav/grav-theme-lingonberry/blob/develop/templates/partials/header.html.twig#L4 that  it's grabbed from `site.author.gravatar`. Add your email in that field, in user/config/site.yaml

**Comment by ghost** [comment]
It looks like that is populated and it is still not working.

<img width="269" alt="screenshot 2015-12-29 10 21 23" src="https://cloud.githubusercontent.com/assets/9561913/12036651/fec6a382-ae15-11e5-9b37-b08ba58c07f2.png">

**Comment by flaviocopes** [comment]
It uses `site.author.gravatar` not `site.author.email`. So you can just add that option.

**Comment by ghost** [comment]
Sorry about that. Thanks for your help!
