### ISSUE TITLE
Post type doesn't look like demo

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-theme-lingonberry#2]
I have a home page which lists my blog posts. The home page uses the template "blog". Each post is a child of the home page and uses the template "item" but those pages look different from what is on the demo. Each post still has the line going down the side and also has a dark blue background on the left side of the post. What am I doing wrong? Here is a post to show you:

http://dericcain.com/blog/deploying-laravel-5-with-rocketeer

**Comment by flaviocopes** [comment]
Replicated, the single post has that bar on the left, while the posts list is fine.

**Comment by ghost** [comment]
Thanks for your response, however, I'm not sure I understand. Was there an update that made the single post look different from this:

http://demo.getgrav.org/lingonberry-skeleton/blog/drink-more-coffee-developers

If so, then there is a CSS issue because of the line `.content:after` line that is showing on the page. See here:

![screenshot 2016-01-02 10 45 20](https://cloud.githubusercontent.com/assets/9561913/12074959/f310f242-b13d-11e5-9031-ef9a8b66a87a.png)

**Comment by flaviocopes** [comment]
Sorry I didn't see the demo, but I tried the theme on my site, and I got the same blue bar in the single blog post view. But it's not on the demo, so (same as you) I'm not sure what I'm doing wrong.

**Comment by hexplor** [comment]
In post header add following body classes: single single-post. Take a look:

``` yaml
body_classes: single single-post
```
