### ISSUE TITLE
How do I remove the 'Error Page' from the top menu

### ISSUE THREAD

**Issue by pixelpunch** [getgrav/grav-theme-lingonberry#7]
I can create new pages with link on the main top menu, but how do I remove the "Error Page" link? It is not defined as a part of the user/pages directory. I want to retain the 'Error' plugin functionality.

Thanks in advance.

**Comment by flaviocopes** [comment]
I tried installing the theme but the error page is not in the menu.

Quickest way to recreate is to zip your `user/` folder and PM it to me via https://gitter.im/flaviocopes

**Comment by pixelpunch** [comment]
Hi Flavio,
I have found the place where 'Error Page' was defined. In user/config/site.yaml as 

```
menu:
  - url: error
    text: Error Page
```

I am all good now. 
Another question - can I use the Lingonberry skeleton in a commercial project without ascribing any credits?
Thanks for all the support.

**Comment by flaviocopes** [comment]
Oh right in the skeleton. I guess it's to show how the error page looks like.

As for credits, it's the port of http://www.andersnoren.se/teman/lingonberry-wordpress-theme/, not sure what's the licensing of the design on commercial projects actually.
